name: Run Parser

on:
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run parser
        run: bundle exec rake parse:all
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHAT_ID_FOR_SELL: ${{ secrets.TELEGRAM_CHAT_ID_FOR_SELL }}
          RAILS_ENV: production
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          PARSER_URLS: ${{ secrets.PARSER_URLS }}
          PARSER_URLS_FOR_SELL: ${{ secrets.PARSER_URLS_FOR_SELL }}
